SS/events
SRM-ACM-Women/ACM-W-Official-Website pull request #2
Opened 2022-02-09 13:23 UTC by sinjini05

2022-02-09 15:14 UTC, sanskritikhare142 requested changes

2022-02-09 15:14 UTC, sanskritikhare142 commented on css/events.css
> +    width: 169px;
I think you should give dimensions in either `%` or try using `@media` query so that the images are responsive. Did you check responsiveness as of now?

2022-02-09 15:14 UTC, sanskritikhare142 commented on css/events.css
> +
Use prettier to format the files, so that there are no extra spaces and code is in same format throughout.

2022-02-09 15:14 UTC, sanskritikhare142 commented on events.html
> +                    <div><img src="assets/events/IIClogo.png"></div></div>
Using relative path everywhere is better practice, there are lesser chances of your code breaker. So try using relative paths in all src tags. It goes something like `./assets/events/imagename.png`

2022-02-09 15:14 UTC, sanskritikhare142 commented on events.html
> +                    <div><img src="assets/events/IIClogo.png"></div></div>
I don't think you require two `div` tags here.  The `div` without any class is redundant I guess.

2022-02-09 15:29 UTC, sinjini05 commented on css/events.css
> +    width: 169px;
I checked it just now and its not responsive. I'll change it.

2022-02-16 16:29 UTC, sanskritikhare142 commented on css/events.css
> +
Did you use prettier to format the files in the recent changes?

2022-02-16 17:53 UTC, sinjini05 commented on css/events.css
> +
no, I forgot to change the settings, my bad. I formatted the document using prettier in the most latest ones.

2022-02-16 18:00 UTC, merged