changes in FAQs
SRM-ACM-Women/ACM-W-Official-Website pull request #3
Opened 2022-02-10 05:44 UTC by aastha170902

Changes made to the Resources page and Join us page.

2022-02-10 15:09 UTC, sanskritikhare142 requested changes

2022-02-10 15:09 UTC, sanskritikhare142 commented on join.html
> +Some of the perks of being a  member out of many include : <br>
Please use prettier to format all the files

2022-02-10 15:09 UTC, sanskritikhare142 commented on news.html
> +        <br>
`br` is a self-closing tag. Please change the syntax or remove it if it is redundant.

2022-02-10 15:09 UTC, sanskritikhare142 commented on join.html
> -                <svg
I think removing this `svg` tag would be throwing some errors. The closing tag is still present and the image too. So the opening tag should also be present. Did you check the console for error message?

2022-02-10 15:09 UTC, sanskritikhare142 commented on join.html
> +1. Access to the full ACM Digital Library. <br>
Avoid using `<br/>` tag for changing lines. Rather wrap it in a fluid container. Also check if the text is responsive.

2022-02-10 15:17 UTC, aastha170902 commented on join.html
> +Some of the perks of being a  member out of many include : <br>
okay

2022-02-10 15:18 UTC, aastha170902 commented on news.html
> +        <br>
I'll look into it.

2022-02-10 15:19 UTC, aastha170902 commented on join.html
> -                <svg
No I didn't, I'll do that

2022-02-10 15:19 UTC, aastha170902 commented on join.html
> +1. Access to the full ACM Digital Library. <br>
okay okay

2022-02-16 17:42 UTC, sanskritikhare142 requested changes

2022-02-16 17:42 UTC, sanskritikhare142 commented on join.html
> +              Some of the perks of being a member out of many include : <br>
Please check the syntax of `br` tag.

2022-02-20 18:51 UTC, aastha170902 commented on join.html
> +              Some of the perks of being a member out of many include : <br>
done

2022-02-20 19:11 UTC, merged